parameters:
    # Admin siteaccess group name
    admin_group_name: admin_group

ezplatform:
    siteaccess:
        list: [admin]
        groups:
            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin]

    system:
        admin_group:
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            # For admin this needs to contain all languages you want to translate content to on the given repository.
            languages: [eng-GB]
            content_tree_module:
                contextual_tree_root_location_ids:
                    - 2 # Home (Content structure)
                    - 5 # Users
                    - 43 # Media
                    - 48 # Setup
            subtree_paths:
                content: /1/2/
                media: /1/43/
            assets:
                icon_sets:
                    default_icons: /bundles/ezplatformadminui/img/ez-icons.svg
                default_icon_set: default_icons
